export const siteConfig = {
  name: "DevOps Training",
  description: "Professional DevOps training programs covering Kubernetes, CI/CD, Terraform, AWS, and complete DevOps engineering skills. Hands-on labs, live sessions, and job placement assistance.",
  tagline: "Master DevOps with hands-on training.",
  url: "https://devopstraining.com",
  
  contact: {
    whatsapp: "+919000605565",
    phone: "+919000605565",
    email: "sravanjillala97@gmail.com",
    telegram: "devopssupport",
  },

  hero: {
    headline: "Master DevOps with Professional Training Programs",
    subtext: "Learn Kubernetes, CI/CD, Terraform, AWS, and complete DevOps engineering with hands-on labs, live sessions, and expert mentorship.",
    cta1: "Explore Programs",
    cta2: "Get Free Consultation",
  },

  trustSignals: [
    { text: "Live instructor-led sessions", icon: "users" },
    { text: "Hands-on labs & projects", icon: "code" },
    { text: "Industry expert trainers", icon: "award" },
    { text: "Job placement assistance", icon: "briefcase" },
  ],

  services: [
    {
      id: "cicd",
      title: "CI/CD Support",
      description: "Get help with Jenkins, GitHub Actions, GitLab CI, and Argo CD pipelines.",
      icon: "git-branch",
      details: [
        "Pipeline creation and optimization",
        "Build and deployment automation",
        "Integration with multiple tools",
        "Troubleshooting failed builds",
      ],
      typicalIssues: [
        "Pipeline stuck or failing intermittently",
        "Slow build times need optimization",
        "Need to set up multi-environment deployments",
        "Integration with testing and security tools",
        "Migration from one CI/CD platform to another",
      ],
    },
    {
      id: "kubernetes",
      title: "Kubernetes & Docker Support",
      description: "Expert assistance with containerization, orchestration, and cluster management.",
      icon: "container",
      details: [
        "Dockerfile optimization",
        "Kubernetes deployments and services",
        "Helm charts and package management",
        "Troubleshooting pod crashes and networking",
      ],
      typicalIssues: [
        "Pods crashing or in CrashLoopBackOff",
        "Services not accessible or networking issues",
        "Resource limits causing OOMKilled errors",
        "ConfigMaps and Secrets not mounting properly",
        "Need to set up ingress controllers and load balancing",
      ],
    },
    {
      id: "terraform",
      title: "Terraform / IaC Support",
      description: "Infrastructure as Code help for Terraform, CloudFormation, and Ansible.",
      icon: "code",
      details: [
        "Writing and organizing Terraform modules",
        "State management and remote backends",
        "Resource provisioning and updates",
        "Migration to Infrastructure as Code",
      ],
      typicalIssues: [
        "Terraform state locked or corrupted",
        "Resources not updating as expected",
        "Need to modularize existing infrastructure code",
        "Import existing resources into Terraform",
        "Setting up workspaces for multi-environment management",
      ],
    },
    {
      id: "cloud",
      title: "Cloud Support (AWS/Azure)",
      description: "Practical help with AWS and Azure services and architecture.",
      icon: "cloud",
      details: [
        "EC2, S3, Lambda, RDS basics",
        "IAM roles and security best practices",
        "Networking (VPC, subnets, security groups)",
        "Cost optimization tips",
      ],
      typicalIssues: [
        "Permission denied or IAM role issues",
        "Application can't connect to database",
        "High cloud costs need optimization",
        "Setting up VPC and secure networking",
        "Lambda function timing out or errors",
      ],
    },
    {
      id: "monitoring",
      title: "Monitoring & Logging",
      description: "Set up and troubleshoot Prometheus, Grafana, ELK, and other observability tools.",
      icon: "activity",
      details: [
        "Prometheus metrics and alerts",
        "Grafana dashboard creation",
        "Centralized logging with ELK/Loki",
        "Application performance monitoring",
      ],
      typicalIssues: [
        "Metrics not appearing in Grafana",
        "Alerts not firing when they should",
        "Logs not being collected properly",
        "Need custom dashboards for specific services",
        "High cardinality metrics causing performance issues",
      ],
    },
    {
      id: "incident",
      title: "Release/Incident Support",
      description: "On-call assistance during critical releases, incidents, and production troubleshooting.",
      icon: "alert-circle",
      details: [
        "Real-time troubleshooting during incidents",
        "Release support and rollback procedures",
        "Root cause analysis and documentation",
        "Performance tuning under pressure",
      ],
      typicalIssues: [
        "Production down, need immediate help",
        "Release deployment failing mid-way",
        "Performance degradation after deployment",
        "Need to investigate and fix memory leaks",
        "Database query performance issues",
      ],
    },
  ],

  trainingPrograms: [
    {
      id: "devops-fundamentals",
      title: "DevOps Deep Dive",
      description: "Complete beginner to intermediate DevOps training covering essential tools and practices.",
      icon: "graduation-cap",
      duration: "8 weeks",
      level: "Beginner to Intermediate",
      topics: [
        "Linux command line & shell scripting",
        "Git & GitHub workflows",
        "Jenkins CI/CD pipelines",
        "Docker & Kubernetes essentials",
        "Prometheus, Grafana & Alertmanager monitoring",
        "Cloud platforms: AWS, Azure, GCP",
      ],
      features: [
        "Live instructor-led sessions",
        "Hands-on labs and projects",
        "Lifetime access to materials",
        "Certificate of completion",
      ],
    },
    {
      id: "kubernetes-mastery",
      title: "Docker & Kubernetes Mastery",
      description: "Deep dive into Kubernetes architecture, deployment strategies, and production best practices.",
      icon: "box",
      duration: "6 weeks",
      level: "Intermediate to Advanced",
      topics: [
        "Kubernetes basics and architecture",
        "Pods, deployments, and services",
        "ConfigMaps, Secrets, and volumes",
        "Helm charts and package management",
        "Kubernetes on cloud (EKS / AKS / GKE)",
        "Production troubleshooting and monitoring",
      ],
      features: [
        "Advanced hands-on labs",
        "Production use case studies",
        "Interview preparation",
        "Certificate of completion",
      ],
    },
    {
      id: "cicd-expert",
      title: "CI/CD Pipeline Expert",
      description: "Master modern CI/CD pipelines with Jenkins, GitLab CI, GitHub Actions, and Argo CD.",
      icon: "git-pull-request",
      duration: "4 weeks",
      level: "Intermediate",
      topics: [
        "CI/CD concepts and pipeline fundamentals",
        "Jenkins pipeline creation and automation",
        "GitHub Actions and GitLab CI/CD",
        "Docker image build and registry management",
        "Kubernetes deployments using CI/CD",
        "Multi-cloud deployments (AWS, Azure, GCP)",
      ],
      features: [
        "Build real CI/CD pipelines",
        "GitOps workflow training",
        "Real company scenarios",
        "Certificate of completion",
      ],
    },
    {
      id: "terraform-iac",
      title: "Terraform & IaC Mastery",
      description: "Comprehensive Infrastructure as Code training with Terraform, AWS, and best practices.",
      icon: "code",
      duration: "5 weeks",
      level: "Intermediate",
      topics: [
        "Terraform basics and core concepts",
        "Providers, resources, and state management",
        "Remote backend configuration",
        "Terraform modules and reusability",
        "Terraform workspace management",
        "Security and best practices",
      ],
      features: [
        "Real infrastructure projects",
        "Multi-cloud hands-on practice",
        "Module library creation",
        "Certificate of completion",
      ],
    },
    {
      id: "complete-devops",
      title: "AWS Administrator",
      description: "Comprehensive AWS administration training covering cloud infrastructure, services, and best practices.",
      icon: "cloud",
      duration: "16 weeks",
      level: "Beginner to Advanced",
      topics: [
        "AWS fundamentals and core services",
        "EC2, VPC, and networking in AWS",
        "S3, EBS, and storage solutions",
        "IAM, security, and compliance",
        "Load balancing and auto-scaling",
        "CloudWatch and cost optimization",
      ],
      features: [
        "Complete AWS curriculum",
        "20+ hands-on AWS projects",
        "Real-world cloud scenarios",
        "Certificate of completion",
      ],
    },
    {
      id: "one-on-one-sessions",
      title: "Azure Administrator",
      description: "Comprehensive Azure administration training covering cloud infrastructure, services, and management.",
      icon: "cloud-cog",
      duration: "16 weeks",
      level: "Beginner to Advanced",
      topics: [
        "Azure fundamentals and core services",
        "Virtual machines and compute resources",
        "Azure networking and VNet configuration",
        "Azure storage and data management",
        "Azure Active Directory and identity",
        "Monitoring, security, and cost optimization",
      ],
      features: [
        "Complete Azure curriculum",
        "20+ hands-on Azure projects",
        "Real-world cloud scenarios",
        "Certificate of completion",
      ],
    },
    {
      id: "gcp-administrator",
      title: "GCP Administrator",
      description: "Comprehensive Google Cloud Platform administration training covering cloud infrastructure, services, and management.",
      icon: "cloud-lightning",
      duration: "16 weeks",
      level: "Beginner to Advanced",
      topics: [
        "GCP fundamentals and core services",
        "Compute Engine and VM management",
        "GCP networking and VPC configuration",
        "Cloud storage and data services",
        "IAM, security, and Cloud Operations",
        "GKE and cost optimization",
      ],
      features: [
        "Complete GCP curriculum",
        "20+ hands-on GCP projects",
        "Real-world cloud scenarios",
        "Certificate of completion",
      ],
    },
    {
      id: "multi-cloud-devops",
      title: "Multi-Cloud DevOps",
      description: "Master DevOps practices across AWS, Azure, and GCP with unified CI/CD, infrastructure as code, and monitoring strategies.",
      icon: "cloud",
      duration: "20 weeks",
      level: "Advanced",
      topics: [
        "Multi-cloud fundamentals and architecture",
        "Comparing AWS, Azure, and GCP services",
        "Terraform for multi-cloud infrastructure",
        "Kubernetes on EKS, AKS, and GKE",
        "CI/CD for multi-cloud deployments",
        "Security and cost optimization",
      ],
      features: [
        "Comprehensive multi-cloud training",
        "30+ hands-on cross-cloud projects",
        "Hybrid cloud architecture design",
        "Certificate of completion",
      ],
    },
  ],

  howItWorks: [
    {
      step: 1,
      title: "Share Your Issue",
      description: "Reach out via WhatsApp, call, or email with your problem or requirement.",
      icon: "message-square",
    },
    {
      step: 2,
      title: "Screen Share Session",
      description: "We join you on a call and guide you through the solution step-by-step.",
      icon: "screen-share",
    },
    {
      step: 3,
      title: "Fix & Explain",
      description: "We help implement the fix, explain the why, and ensure you understand the approach.",
      icon: "wrench",
    },
    {
      step: 4,
      title: "Documentation",
      description: "You get scripts, commands, RCA notes, and best practice documentation.",
      icon: "file-text",
    },
    {
      step: 5,
      title: "Follow-up Support",
      description: "Quick follow-up if you face related issues within the support window.",
      icon: "refresh-cw",
    },
  ],

  benefits: [
    "Reusable scripts and automation templates",
    "Best practices and production-ready patterns",
    "Root cause analysis notes",
    "Pipeline and deployment templates",
    "Configuration samples and examples",
    "Troubleshooting checklists",
  ],

  tools: [
    { name: "Linux", icon: "terminal" },
    { name: "Git", icon: "git-branch" },
    { name: "Docker", icon: "container" },
    { name: "Kubernetes", icon: "box" },
    { name: "Helm", icon: "package" },
    { name: "Terraform", icon: "code" },
    { name: "Ansible", icon: "settings" },
    { name: "Jenkins", icon: "circle" },
    { name: "GitHub Actions", icon: "github" },
    { name: "Argo CD", icon: "git-pull-request" },
    { name: "Prometheus", icon: "activity" },
    { name: "Grafana", icon: "bar-chart" },
    { name: "ELK Stack", icon: "search" },
    { name: "AWS", icon: "cloud" },
  ],

  pricing: {
    tiers: [
      {
        id: "hourly",
        name: "Hourly Support",
        price: "$50",
        period: "per hour",
        description: "Perfect for one-off issues or quick help",
        features: [
          "Pay as you go",
          "Screen share guidance",
          "Documentation provided",
          "Best for single issues",
          "Response within 2-4 hours",
          "Email and chat support",
        ],
        cta: "Get Started",
        highlighted: false,
      },
      {
        id: "weekly",
        name: "Weekly Plan",
        price: "$300",
        period: "per week",
        description: "Best for ongoing projects or multiple issues",
        features: [
          "Up to 8 hours support",
          "Priority response (< 1 hour)",
          "Screen share + code review",
          "WhatsApp/Call/Email support",
          "RCA documentation",
          "Follow-up within the week",
        ],
        cta: "Best Value",
        highlighted: true,
      },
      {
        id: "monthly",
        name: "Monthly Plan",
        price: "$1000",
        period: "per month",
        description: "For teams needing regular DevOps guidance",
        features: [
          "Up to 30 hours support",
          "Immediate response (< 30 min)",
          "Dedicated support hours",
          "All communication channels",
          "Custom scripts & automation",
          "Proactive suggestions",
          "Release planning support",
        ],
        cta: "Contact Us",
        highlighted: false,
      },
    ],
    disclaimer: "We guide you with best practices; outcomes depend on your environment and access.",
    customPlanText: "Need a custom plan? We offer tailored packages for teams and enterprises.",
  },

  testimonials: [
    {
      id: 1,
      name: "Raj Kumar",
      role: "DevOps Engineer at Tech Corp",
      content: "Saved my job! I was stuck on a Kubernetes networking issue for 2 days. They helped me fix it in 30 minutes and explained everything clearly.",
      rating: 5,
      avatar: "RK",
    },
    {
      id: 2,
      name: "Sarah Chen",
      role: "Cloud Engineer at StartupXYZ",
      content: "The monthly plan is worth every penny. I get help whenever I'm stuck, and I've learned so much from their guidance.",
      rating: 5,
      avatar: "SC",
    },
    {
      id: 3,
      name: "Amit Sharma",
      role: "Junior DevOps at FinTech Inc",
      content: "As a fresher, I was overwhelmed with production issues. Their step-by-step guidance helped me deliver my first successful release.",
      rating: 5,
      avatar: "AS",
    },
    {
      id: 4,
      name: "Michael Brown",
      role: "SRE at Enterprise Solutions",
      content: "Fast, professional, and they actually care about teaching you. Not just fixing the problem but making sure you understand it.",
      rating: 5,
      avatar: "MB",
    },
    {
      id: 5,
      name: "Priya Patel",
      role: "DevOps Lead at E-commerce Co",
      content: "Used them during a critical production incident. They stayed with us until everything was resolved. Highly recommended!",
      rating: 5,
      avatar: "PP",
    },
    {
      id: 6,
      name: "David Lee",
      role: "Platform Engineer at SaaS Company",
      content: "Their Terraform support helped us migrate our entire infrastructure to IaC. Great documentation and best practices.",
      rating: 5,
      avatar: "DL",
    },
  ],

  faqs: [
    {
      id: 1,
      question: "What are the class timings?",
      answer: "We offer flexible timings with both weekday and weekend batches. Weekday batches run from 7 PM to 9 PM IST, and weekend batches run on Saturdays and Sundays from 10 AM to 1 PM IST. We also offer personalized one-on-one sessions at your preferred time.",
    },
    {
      id: 2,
      question: "Do I need any prior experience to join?",
      answer: "For our DevOps Deep Dive course, no prior DevOps experience is required. Basic knowledge of Linux and command line is helpful. For advanced courses like Docker & Kubernetes Mastery, we recommend having some foundational DevOps knowledge.",
    },
    {
      id: 3,
      question: "Will I get hands-on practice?",
      answer: "Absolutely! All our programs include extensive hands-on labs, real-world projects, and practical exercises. You'll work with actual DevOps tools and scenarios that you'll encounter in the industry.",
    },
    {
      id: 4,
      question: "Do you provide job placement assistance?",
      answer: "Yes! Our Complete DevOps Engineer program includes comprehensive job placement assistance with resume building, interview preparation, mock interviews, and referrals to our partner companies.",
    },
    {
      id: 5,
      question: "What if I miss a class?",
      answer: "Don't worry! All live sessions are recorded and shared with you for lifetime access. You can watch the recording at your convenience. We also offer doubt-clearing sessions to help you catch up.",
    },
    {
      id: 6,
      question: "Will I get a certificate?",
      answer: "Yes! Upon successful completion of the program, you'll receive a certificate of completion. For the Complete DevOps Engineer program, you'll also get a verified digital certificate that you can showcase on LinkedIn.",
    },
    {
      id: 7,
      question: "What is the refund policy?",
      answer: "We offer a 7-day money-back guarantee. If you're not satisfied with the program quality within the first week, we'll provide a full refund—no questions asked.",
    },
    {
      id: 8,
      question: "Can I get one-on-one mentorship?",
      answer: "Yes! All our programs include access to expert mentors. You can schedule one-on-one doubt-clearing sessions, get personalized guidance on projects, and receive career advice throughout your learning journey.",
    },
  ],

  footer: {
    description: "Professional DevOps Training and Job support for engineers who need real-time help with CI/CD, Kubernetes, cloud deployments, and production issues.",
    quickLinks: [
      { name: "Home", href: "/" },
      { name: "Services", href: "/services" },
      { name: "Pricing", href: "/pricing" },
      { name: "Contact", href: "/contact" },
    ],
    services: [
      { name: "DevOps Training", href: "/#training" },
      { name: "Cloud Training (AWS/AZURE/GCP)", href: "/#training" },
      { name: "DevOps Job Support", href: "/services" },
    ],
    legal: [
      { name: "Privacy Policy", href: "#" },
      { name: "Terms of Service", href: "#" },
      { name: "Refund Policy", href: "#" },
    ],
  },
};

export type SiteConfig = typeof siteConfig;
